from __future__ import annotations

import json
from pathlib import Path

from fastapi import FastAPI, HTTPException

app = FastAPI(title="Vehicle Analytics API")


@app.get("/health")
def health() -> dict:
    return {"ok": True}


@app.get("/api/analytics")
def get_analytics() -> dict:
    """Returns the latest analytics JSON generated by backend.scripts.count_video.

    By default it reads: backend/output/counts.json
    """

    path = Path("backend") / "output" / "counts.json"
    if not path.exists():
        raise HTTPException(status_code=404, detail="counts.json not found. Run the counting script first.")

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise HTTPException(status_code=500, detail=f"Invalid JSON in counts.json: {e}")
